---
- include: elasticsearch-xpack-install.yml

#Security configuration
- include: security/elasticsearch-security.yml

#Add any feature specific configuration here
- name: Set Plugin Directory Permissions
  become: yes
  file: state=directory path={{ es_home }}/plugins owner={{ es_user }} group={{ es_group }} recurse=yes
